### ISSUE TITLE
crashes on android 6.0

### ISSUE THREAD

**Issue by viktoschi** [timomer/HAPP#7] opened 2015-12-10 16:16 UTC
happ crashes on android 6.0
but it is still collecting data in background

**Comment by timomer** [comment] 2015-12-12 16:18
Do you think this is only with Android 6?

I have a few fatal bugs to fix this weekend, once done checkout the new version and see if you still have an issue

**Comment by timomer** [comment] 2015-12-13 10:23
This has bee fixed in 1.2.6, reopen if you still have an issue

**Comment by viktoschi** [comment] 2015-12-14 17:31
good work no it is running most of the time...
do not know if it is a android6.0 problem...
if i press accept temp notification (not in the app) or accept temp in notification area or the notification android wear watch -> happ crashes. 
it only works if i press the accept temp button in the app.

**Comment by timomer** [comment] 2015-12-15 10:01
Cool, I have seen the crash report - will check it out and report back

**Comment by timomer** [comment] 2015-12-21 20:05
checkout 1.2.7 - the issue is down to the way Android 6 processes gson

**Closed as completed by timomer** 2015-12-21 20:05 UTC
